toml: allow inline comments in multiline arrays
tweag/topiary pull request #624
Opened 2023-09-09 08:58 UTC by pjjw

previously, if you had comments on individual items in a multiline
array, e.g.

```toml
children = [
  "michael",
  "gob", # i don't care too much for this one
  "lindsay",
]
```

topiary would confusingly move the comment _below_ the element it was
placed next to-

```toml
children = [
  "michael",
  "gob",
  # i don't care too much for this one
  "lindsay",
]
```
which can destroy the intent of the comment. this rule update now
preserves inline comments and won't insert a linebreak after a separator
if followed by one.

2023-09-13 10:11 UTC, nbacquey requested changes

2023-09-13 10:11 UTC, nbacquey commented on topiary/tests/samples/expected/toml.toml
> +["inline.comments"]
I think we should add the `inline.comments` section alongside `unzip`, instead of replacing it

2023-09-13 10:11 UTC, nbacquey commented on topiary/tests/samples/input/toml.toml
> +["inline.comments"]
Ditto here

2023-09-14 09:59 UTC, pjjw commented on topiary/languages/toml.scm
> +    (_)
oh, thanks for the pointer! absolutely new at tree-sitter queries.

2023-09-14 10:11 UTC, pjjw commented
@nbacquey thanks for the pointers! let me know if i've addressed comments to satisfaction.

2023-09-14 11:26 UTC, nbacquey approved these changes
Looks good to me. Thanks for contributing!

2023-09-14 11:27 UTC, nbacquey commented on topiary/tests/samples/expected/toml.toml
> +["inline.comments"]
I didn't notice that you were the original author of this section ; my bad.

2023-09-14 11:27 UTC, merged