[Nickel] Add support for extended patterns
tweag/topiary pull request #705
Opened 2024-05-28 16:05 UTC by yannham

# Extended patterns

This PR adds support for the last train of new pattern features in current Nickel: wildcard patterns, or-patterns, array patterns and pattern guards.

## Description

Update to latest Nickel tree-sitter grammar and add queries to format the new constructs.

## Checklist

Checklist before merging:
- [ ] CHANGELOG.md updated
- [ ] README.md up-to-date

2024-05-30 15:12 UTC, Xophmeister requested changes
The changes look good, but I would suggest:

@yannham Can some example code that hit your new formatting rules be added to `topiary-cli/tests/samples/{input,expected}/nickel.ncl` so they are tested?

@ErinvanderVeen I would cherry-pick your changes to `bin/update-wasm-grammars.sh` into a separate PR -- along with the updates to the _non_-Nickel WASM grammars -- so this PR can be more focused.

2024-05-30 15:12 UTC, Xophmeister commented on bin/update-wasm-grammars.sh
> +mkdir -p $WORKDIR
It's worth adding a comment here as to why `mktemp` doesn't work in general.

2024-05-30 15:12 UTC, Xophmeister commented on bin/update-wasm-grammars.sh
> +trap 'echo -e "${BLUE}Cleanup...${NC}"; rm -rf "${WORKDIR}"; rm a.out.{js,wasm}' EXIT
```suggestion
trap 'echo -e "${BLUE}Cleanup...${NC}"; rm -rf "${WORKDIR}" a.out.{js,wasm}' EXIT
```

2024-05-30 16:16 UTC, ErinvanderVeen commented
> @yannham Can some example code that hit your new formatting rules be added to `topiary-cli/tests/samples/{input,expected}/nickel.ncl` so they are tested?

The new tests were blocked because there was an issue in the tree-sitter grammar. Yann has resolved this issue, but it still needs to merged.

2024-05-31 09:31 UTC, yannham commented
If I understood correctly, @ErinvanderVeen is willing to take over and to take this PR to the finish line.

2024-06-04 17:39 UTC, yannham commented
In fact I'm going to take over again, as this is blocking for the next Nickel release :slightly_smiling_face:

2024-06-05 10:18 UTC, Xophmeister commented
Looks good... Let me just cherry-pick @ErinvanderVeen's commit into a separate branch before it gets lost. Also, I'll regenerate the Nickel WASM for this PR. Give me a sec, then I'll approve :+1:

2024-06-05 10:23 UTC, Xophmeister approved these changes

2024-06-05 10:48 UTC, merged